select * from filme

DROP TABLE IF EXISTS filme CASCADE;
CREATE TABLE filme (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                       titulo VARCHAR(100) NOT NULL,
                       disponivel boolean NOT NULL,
                       categoria VARCHAR(10) NOT NULL,
                       responsavel VARCHAR(100),
                       data_de_retirada date,
                       url_poster VARCHAR(200) NOT NULL,
                       descricao VARCHAR(1000) NOT NULL,
                       CONSTRAINT ck_movie CHECK (categoria IN ('BRONZE' , 'PRATA', 'OURO')),
                       CONSTRAINT pk_movie PRIMARY KEY (id));